sudo: required
dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - wget -q https://codeload.github.com/glassechidna/zxing-cpp/tar.gz/master -O master.tar.gz
  - tar xzf master.tar.gz
  - cd zxing-cpp-master/
  - mkdir build/
  - cd build/
  - cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release
      -DCMAKE_CXX_FLAGS=-fPIC ..
  - make
  - sudo make install
  - cd ../..
  - rm -rf master.tar.gz zxing-cpp-master
  - make install
script:
  - make lint test clean
deploy:
  provider: pypi
  user:
    secure: lwgPAQQagNgeeo5jfQdUl3H0X2LXyxtbyiOdpGbQMl8W0UH/EUQnvw96RKUK9GKEzBUyT/dd205e3JQNZVoKPrwTydNhiepzIidoj2bT2/+sglUUtwKMqd5+P2c81rsSIQQJsuGFnhGl+cjBChq2LsWFEpg6RvfABP1CbFABju+xq7g5e9BsWEasSKMlMJMyfi7RaBhllBaF86Qu9Hfi9szuPR9zZJBjtX5g1AzNicEd2PiqvNiYI6t29/ESVsMCg/2pGXSq0QpaUE20DpxHX4xT8sxycbLSCQqrkpCHMnQsu/369VT0HUDF1XPon87pquNrRiZtxhQ+khV4pRW08dVBUmzl0oXNT8l86NSiz7dkmN5YHlzMhRABjYun0EqZ/0cj2zmSK/4xTXHojZFtPlNtrrsJG2Hxi1rEAP/A3VwmlJKLcTS3FER9uDHV6afRapT02/xZ1dbpGBpH+zdQV45XCgiHOK2K8VRHPP6Z4rCywuxo0e8Evbyaj0lRPRfqCbKObeSvslPURF+aXqCcZOdTZdQWWs9xKapMMjrnbjuKoVX0KtfQVndbQ1WeBrSPOBQg3GCHzs2wUFSQA37UuqjFc5nyQEbm5vtOKqYG8ON1rz39A11wvTUrcuZ4wZ5FrJ+f8EFIQG8Y8VHZNx5FKWJIxQIOxDGkVvRLXit0QXw=
  password:
    secure: JhrmBJio3fmp8RxzzSKtgb/6JGu9ZFQeq2Fo/FXi3gHlqp6Ov2OPcFLs4a/jLbwFoLLsvuCfKUqW03HAKOrSEZ3MGteZioB7vwImQgesBogn6v/T+QwENYDQlIc4+R7jXfQDRRdwjgJ3PMRwZISf2+0WIqo7hFaWaYvn+jxJ7bxEgQUVww7W9TldSJ6Jx7IO6zVfzdjkWdRWinyv63UVF1dpFygf/G5JE/5tNqHvrmfVjZvYXiE5VYenwus9VwFoqLaq+BNHJsBROEZvH7Gm0Zry8lgr+jCO3so4XMlMJDG1hwQv9PlzUDpeJliojMiD332xHp36gqKTNg9OSJUVssbMZQifXeYEhaXAVirHTjhigVH2uJ0uWg3TcbNA9FQN3moIbZ7SBDsAPNAWgGS3aCZPE9gvVTIFSssDHTcNHJlk/fw0BiYq9/ZoZZ+z9QamKP0DooC1mWOlZGeQYBBWGaF5SVlQnBEI2bpyRO/8pTLSoBXjD6FqCI9y3OhLL2nWOrduko3eHpXL3OdNXa/Y/nWP2wULSZ4C3yzpSOjrACyaKUiKKn9Assy72kuNg7lPXWyN/YqoaYFv/hrox9+LvpyqbH6DYwTyibmgdG1ykDxuxBMnylDj8wHWU8w41mg/zVP1CmyMcCxoI7WL6+9TYqZ7nTN7yR8WOHFoDlGH+V4=
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = '3.7'"
